# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [1]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

NameError: name 'np' is not defined

Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [2]:
import random
print(''.join([random.choice(list('0123456789')) for x in range(1)]))



4


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [3]:
import numpy as np
import random
m,n = 4,6
matrix = [[random.randrange(0,10) for y in range(m)] for x in range(n)]
print('matrix=',matrix )



matrix= [[8, 3, 9, 7], [8, 4, 6, 5], [7, 5, 0, 9], [2, 0, 9, 1], [4, 0, 7, 0], [6, 0, 1, 3]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [4]:
a=np.random.randint(0,10)
print('случайное число:',a)



случайное число: 3


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [5]:
import random
m,n = 4,5
matrix = [[random.randint(10,100) for y in range(m)] for x in range(n)]
print('matrix=',matrix )



matrix= [[87, 100, 67, 80], [53, 57, 25, 33], [85, 31, 39, 14], [38, 45, 25, 62], [22, 94, 63, 31]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [9]:
import numpy as np
m,n = 3,4
matrix = [np.random.sample(m) for y in range(n)] 
print('matrix=',matrix )



Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [6]:
b=5
a=3
np.random.sample(size=10)*(b-a)+a



array([4.69462796, 4.41258714, 4.88113836, 3.69164908, 4.11245185,
       4.91726318, 3.57013905, 3.63880598, 3.2087726 , 4.20153482])

### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [13]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
M = np.arange(20).reshape((4, 5))
a=np.random.shuffle(M)
print(a)



## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [22]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H']


In [23]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

6 heads and 4 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))



### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [25]:
tosses= np.random.randint(2,size=100)
heads=sum(tosses==1)
tails=sum(tosses==0)
print ("Орлов", heads)
print ("Решек", tails)


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [7]:
tosses= np.round(np.random.sample(100))
heads=sum(tosses==1)
tails=sum(tosses==0)
print ("Орлов", heads)
print ("Решек", tails)



Орлов 44
Решек 56


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [8]:
params=[10,50,100,250,500,1000,2500,5000,10000 ]
for n in params:
    tosses= np.round(np.random.sample(n))
    heads=sum(tosses==1)
    a=heads/n
    print('емпірична ймовірність',a)



емпірична ймовірність 0.9
емпірична ймовірність 0.52
емпірична ймовірність 0.52
емпірична ймовірність 0.508
емпірична ймовірність 0.498
емпірична ймовірність 0.488
емпірична ймовірність 0.5044
емпірична ймовірність 0.4946
емпірична ймовірність 0.5027


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [10]:
dies=np.random.randint(low=1, high=7, size=60)
for i in np.arange(1,7):
    print('{}:{}'.format(i, sum(dies==1)))



1:10
2:10
3:10
4:10
5:10
6:10


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [9]:
params=[10,50,100,250,500,1000,2500,5000,10000 ]
for n in params:
    dies=np.random.randint(low=1, high=7, size=n)
    b=sum(dies==1)
    a=b/n
    print('емпірична ймовірність',a)



емпірична ймовірність 0.5
емпірична ймовірність 0.18
емпірична ймовірність 0.14
емпірична ймовірність 0.136
емпірична ймовірність 0.158
емпірична ймовірність 0.18
емпірична ймовірність 0.156
емпірична ймовірність 0.1652
емпірична ймовірність 0.1616


## 5 Колода карт
### 5.1 Реалізація

In [30]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('3', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('7', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('9', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('5', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('6', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('J', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('4', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('Q', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('8', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('10', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('1', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('2', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('K', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢')]


In [31]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

3♣, 3♠, 3♡, 3♢, 7♣, 7♠, 7♡, 7♢, 9♣, 9♠, 9♡, 9♢, 5♣, 5♠, 5♡, 5♢, 6♣, 6♠, 6♡, 6♢, J♣, J♠, J♡, J♢, 4♣, 4♠, 4♡, 4♢, Q♣, Q♠, Q♡, Q♢, 8♣, 8♠, 8♡, 8♢, 10♣, 10♠, 10♡, 10♢, 1♣, 1♠, 1♡, 1♢, 2♣, 2♠, 2♡, 2♢, K♣, K♠, K♡, K♢


In [32]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣3, ♣7, ♣9, ♣5, ♣6, ♣J, ♣4, ♣Q, ♣8, ♣10, ♣1, ♣2, ♣K
♠3, ♠7, ♠9, ♠5, ♠6, ♠J, ♠4, ♠Q, ♠8, ♠10, ♠1, ♠2, ♠K
♡3, ♡7, ♡9, ♡5, ♡6, ♡J, ♡4, ♡Q, ♡8, ♡10, ♡1, ♡2, ♡K
♢3, ♢7, ♢9, ♢5, ♢6, ♢J, ♢4, ♢Q, ♢8, ♢10, ♢1, ♢2, ♢K


In [33]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♠'), ('10', '♡'), ('3', '♡'), ('2', '♠'), ('2', '♣'), ('10', '♢'), ('J', '♡'), ('1', '♢'), ('9', '♡'), ('3', '♣'), ('6', '♡'), ('Q', '♡'), ('K', '♣'), ('8', '♠'), ('J', '♠'), ('7', '♣'), ('K', '♡'), ('8', '♣'), ('5', '♣'), ('Q', '♢'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('1', '♡'), ('5', '♡'), ('5', '♢'), ('1', '♣'), ('1', '♠'), ('9', '♠'), ('10', '♣'), ('9', '♢'), ('2', '♢'), ('6', '♠'), ('Q', '♣'), ('10', '♠'), ('7', '♠'), ('2', '♡'), ('K', '♢'), ('8', '♢'), ('6', '♣'), ('K', '♠'), ('8', '♡'), ('7', '♢'), ('7', '♡'), ('4', '♢'), ('6', '♢'), ('3', '♠'), ('4', '♠'), ('9', '♣'), ('5', '♠'), ('4', '♣'), ('3', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [34]:
# Місце для Вашого коду



### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [35]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

